package com.liqihao.commons;

public interface ConstantValue {
    //包头
    int FLAG=6617329;

    int BAG_MAX_VALUE=99;

    //场景模块
     String SCENE_MODULE="sceneServiceImpl";
    //请求部分
    //请求可以前往的场景
    int ASK_CAN_REQUEST=1000;
    //请求当前场景的角色
    int FIND_ALL_ROLES_REQUEST=1001;
    //请求前往下一个场景
    int WENT_REQUEST=1002;
    //与npc对话
    int TALK_NPC_REQUEST=1003;
    //响应部分
    //请求可以前往的场景的响应
    int ASK_CAN_RESPONSE=1500;
    //请求当前场景的角色的响应
    int FIND_ALL_ROLES_RESPONSE=1501;
    //请求前往下一个场景的响应
    int WENT_RESPONSE=1502;
    //与npc对话响应
    int TALK_NPC_RESPONSE=1503;
    //玩家模块
    String PLAY_MODULE="playServiceImpl";
    //登陆请求
    int LOGIN_REQUEST=2000;
    //注册请求
    int REGISTER_REQUEST=2001;
    //退出登陆请求
    int LOGOUT_REQUEST=2002;
    int USE_SKILL_REQUEST =2003;
    //response
    //登陆响应
    int LOGIN_RESPONSE=2500;
    //注册响应
    int REGISTER_RESPONSE=2501;
    //退出登陆响应
    int LOGOUT_RESPONSE=2502;
    int USE_SKILL_RSPONSE =2503;
    int DAMAGES_NOTICE_RESPONSE=2504;
    //游戏系统模块
    String GAME_SYSTEM_MODULE="gameSystemServiceImpl";
    //客户端超时请求
    int NET_IO_OUTTIME=3000;
    //客户端超市响应
    int OUT_RIME_RESPONSE=3500;
    //背包模块
    String BAKCPACK_MODULE="backpackServiceImpl";
    int BACKPACK_MSG_REQUEST=4000;
    int USE_REQUEST=4001;
    int ABANDON_REQUEST=4002;
    int ADD_ARTICLE_REQUEST=4003;
    int BACKPACK_MSG_RESPONSE=4500;
    int USE_RESPONSE=4501;
    int ABANDON_RESPONSE=4502;
    int ADD_ARTICLE_RESPONSE=4503;

    //装备模块
    String EQUIPMENT_MODULE="equipmentServiceImpl";
    int ADD_EQUIPMENT_REQUEST=5000;
    int EQUIPMENT_MSG_REQUEST=5001;
    int REDUCE_EQUIPMENT_REQUEST=5002;
    int FIX_EQUIPMENT_REQUEST=5003;

    int ADD_EQUIPMENT_RESPONSE=5500;
    int EQUIPMENT_MSG_RESPONSE=5501;
    int REDUCE_EQUIPMENT_RESPONSE=5502;
    int FIX_EQUIPMENT_RESPONSE=5503;

    //组队系统
    String TEAM_MODULE="teamServiceImpl";
    int CREATE_TEAM_REQUEST=6000;
    int TEAM_MESSAGE_REQUEST=6001;
    int APPLY_FOR_TEAM_REQUEST=6002;
    int INVITE_PEOPLE_REQUEST=6003;
    int APPLY_MESSAGE_REQUEST=6004;
    int INVITE_MESSAGE_REQUEST=6005;
    int REFUSE_APPLY_REQUEST=6006;
    int REFUSE_INVITE_REQUEST=6007;
    int ENTRY_PEOPLE_REQUEST=6008;
    int ENTRY_PEOPLE_REQUEST_INVITE=60088;
    int ENTRY_PEOPLE_REQUEST_APPLY=60089;
    int EXIT_TEAM_REQUEST=6009;
    int BAN_PEOPLE_REQUEST=6010;
    int DELETE_TEAM_REQUEST=6011;

    int BAN_PEOPLE_RESPONSE=6511;
    int DELETE_TEAM_RESPONSE=6512;
    int LEADER_TEAM_RESPONSE=6510;
    int ENTRY_PEOPLE_RESPONSE=6508;
    int EXIT_TEAM_RESPONSE=6509;
    int REFUSE_APPLY_RESPONSE=6506;
    int REFUSE_INVITE_RESPONSE=6507;
    int TEAM_MESSAGE_RESPONSE=6500;
    int APPLY_FOR_TEAM_RESPONSE=6502;
    int INVITE_PEOPLE_RESPONSE=6503;
    int APPLY_MESSAGE_RESPONSE=6004;
    int INVITE_MESSAGE_RESPONSE=6005;

    //副本模块
    String COPY_MODULE="copySceneServiceImpl";
    int ASK_CAN_COPYSCENE_REQUEST=7000;
    int COPYSCENE_MESSAGE_REQUEST=7001;
    int CREATE_COPYSCENE_REQUEST=7002;
    int ENTER_COPYSCENE_REQUEST=7003;
    int EXIT_COPYSCENE_REQUEST=7004;

    int CHANGE_FAIL_RESPONSE=7506;
    int CHANGE_SUCCESS_RESPONSE=7507;
    int ASK_CAN_COPYSCENE_RESPONSE=7500;
    int COPYSCENE_MESSAGE_RESPONSE=7501;
    int CREATE_COPYSCENE_RESPONSE=7502;
    int ENTER_COPYSCENE_RESPONSE=7503;
    int EXIT_COPYSCENE_RESPONSE=7504;
    int COPYSCENE_FINISH_RESPONSE=7505;

    //聊天模块
    int SEND_TO_ALL_REQUEST=8000;
    int SEND_TO_ONE_REQUEST=8001;
    int ACCEPT_MESSAGE_RESPONSE=8500;
    int SEND_TO_TEAM_REQUEST=8002;
    int SEND_TO_SCENE_REQUEST=8003;

    String SEND_TO_TEAM_REQUEST_CMD="sendMessageTeam";
    String SEND_TO_SCENE_REQUEST_CMD="sendMessageScene";
    String SEND_TO_ALL_REQUEST_CMD="sendMessageAll";
    String SEND_TO_ONE_REQUEST_CMD="sendMessageOne";
    String ASK_CAN_COPYSCENE_REQUEST_CMD="askCanCopyScene";
    String COPYSCENE_MESSAGE_REQUEST_CMD="copySceneMsg";
    String CREATE_COPYSCENE_REQUEST_CMD="createCopyScene";
    String ENTER_COPYSCENE_REQUEST_CMD="enterCopyScene";
    String EXIT_COPYSCENE_REQUEST_CMD="exitCopyScene";
    String BAN_PEOPLE_REQUEST_CMD="banPeople";
    String DELETE_TEAM_REQUEST_CMD="deleteTeam";
    String ENTRY_INVITE_PEOPLE_REQUEST_CMD="entryInvitePeople";
    String ENTRY_APPLY_PEOPLE_REQUEST_CMD="entryApplyPeople";
    String EXIT_TEAM_REQUEST_CMD="exitTeam";
    String REFUSE_APPLY_REQUEST_CMD="refuseApply";
    String REFUSE_INVITE_REQUEST_CMD="refuseInvite";
    String APPLY_FOR_TEAM_REQUEST_CMD="applyTeam";
    String INVITE_PEOPLE_REQUEST_CMD="invitePeople";
    String APPLY_MESSAGE_REQUEST_CMD="applyMessage";
    String INVITE_MESSAGE_REQUEST_CMD="inviteMessage";

    String CREATE_TEAM_REQUEST_CMD="createTeam";
    String TEAM_MESSAGE_REQUEST_CMD="getTeamMsg";
    String ADD_EQUIPMENT_REQUEST_CMD="addE";
    String EQUIPMENT_MSG_REQUEST_CMD="EMsg";
    String REDUCE_EQUIPMENT_REQUEST_CMD="reduceE";
    String ASK_CAN_REQUEST_CMD="askCan";
    String FIND_ALL_ROLES_REQUEST_CMD="findAllRoles";
    String WENT_REQUEST_CMD="went";
    String LOGIN_REQUEST_CMD="login";
    String REGISTER_REQUEST_CMD="register";
    String  LOGOUT_REQUEST_CMD="logout";
    String USE_SKILL_REQUEST_CMD="skill";
    String TALK_NPC_REQUEST_CMD="talk";
    String BACKPACK_MSG_REQUEST_CMD="bag";
    String USE_REQUEST_CMD="useA";
    String ABANDON_REQUEST_CMD="abandon";
    String ADD_ARTICLE_REQUEST_CMD="addA";
    String FIX_EQUIPMENT_REQUEST_CMD="fixE";

    int FAIL_RESPONSE=9999;
}
