package com.liqihao.protobufObject;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameSystem.proto

public final class GameSystemModel {
  private GameSystemModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameSystemModelMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameSystemModelMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用date_type来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <pre>
     *用date_type来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
     * @return The dataType.
     */
    GameSystemModelMessage.DateType getDataType();

    /**
     * <code>.OutTimeResponse outTimeResponse = 2;</code>
     * @return Whether the outTimeResponse field is set.
     */
    boolean hasOutTimeResponse();
    /**
     * <code>.OutTimeResponse outTimeResponse = 2;</code>
     * @return The outTimeResponse.
     */
    OutTimeResponse getOutTimeResponse();
    /**
     * <code>.OutTimeResponse outTimeResponse = 2;</code>
     */
    OutTimeResponseOrBuilder getOutTimeResponseOrBuilder();

    public GameSystemModelMessage.DateBodyCase getDateBodyCase();
  }
  /**
   * Protobuf type {@code GameSystemModelMessage}
   */
  public static final class GameSystemModelMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameSystemModelMessage)
      GameSystemModelMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameSystemModelMessage.newBuilder() to construct.
    private GameSystemModelMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameSystemModelMessage() {
      dataType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameSystemModelMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameSystemModelMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              OutTimeResponse.Builder subBuilder = null;
              if (dateBodyCase_ == 2) {
                subBuilder = ((OutTimeResponse) dateBody_).toBuilder();
              }
              dateBody_ =
                  input.readMessage(OutTimeResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((OutTimeResponse) dateBody_);
                dateBody_ = subBuilder.buildPartial();
              }
              dateBodyCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameSystemModel.internal_static_GameSystemModelMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameSystemModel.internal_static_GameSystemModelMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameSystemModelMessage.class, Builder.class);
    }

    /**
     * <pre>
     *定义枚举类型
     * </pre>
     *
     * Protobuf enum {@code GameSystemModelMessage.DateType}
     */
    public enum DateType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *在proto3 要求enum的编号从0开始
       * </pre>
       *
       * <code>OutTimeResponse = 0;</code>
       */
      OutTimeResponse(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *在proto3 要求enum的编号从0开始
       * </pre>
       *
       * <code>OutTimeResponse = 0;</code>
       */
      public static final int OutTimeResponse_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DateType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DateType forNumber(int value) {
        switch (value) {
          case 0: return OutTimeResponse;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DateType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DateType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DateType>() {
              public DateType findValueByNumber(int number) {
                return DateType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return GameSystemModelMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DateType[] VALUES = values();

      public static DateType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DateType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:GameSystemModelMessage.DateType)
    }

    private int dateBodyCase_ = 0;
    private Object dateBody_;
    public enum DateBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      OUTTIMERESPONSE(2),
      DATEBODY_NOT_SET(0);
      private final int value;
      private DateBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DateBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DateBodyCase forNumber(int value) {
        switch (value) {
          case 2: return OUTTIMERESPONSE;
          case 0: return DATEBODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DateBodyCase
    getDateBodyCase() {
      return DateBodyCase.forNumber(
          dateBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     *用date_type来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *用date_type来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
     * @return The dataType.
     */
    @Override public DateType getDataType() {
      @SuppressWarnings("deprecation")
      DateType result = DateType.valueOf(dataType_);
      return result == null ? DateType.UNRECOGNIZED : result;
    }

    public static final int OUTTIMERESPONSE_FIELD_NUMBER = 2;
    /**
     * <code>.OutTimeResponse outTimeResponse = 2;</code>
     * @return Whether the outTimeResponse field is set.
     */
    @Override
    public boolean hasOutTimeResponse() {
      return dateBodyCase_ == 2;
    }
    /**
     * <code>.OutTimeResponse outTimeResponse = 2;</code>
     * @return The outTimeResponse.
     */
    @Override
    public OutTimeResponse getOutTimeResponse() {
      if (dateBodyCase_ == 2) {
         return (OutTimeResponse) dateBody_;
      }
      return OutTimeResponse.getDefaultInstance();
    }
    /**
     * <code>.OutTimeResponse outTimeResponse = 2;</code>
     */
    @Override
    public OutTimeResponseOrBuilder getOutTimeResponseOrBuilder() {
      if (dateBodyCase_ == 2) {
         return (OutTimeResponse) dateBody_;
      }
      return OutTimeResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != DateType.OutTimeResponse.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dateBodyCase_ == 2) {
        output.writeMessage(2, (OutTimeResponse) dateBody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != DateType.OutTimeResponse.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dateBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (OutTimeResponse) dateBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GameSystemModelMessage)) {
        return super.equals(obj);
      }
      GameSystemModelMessage other = (GameSystemModelMessage) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDateBodyCase().equals(other.getDateBodyCase())) return false;
      switch (dateBodyCase_) {
        case 2:
          if (!getOutTimeResponse()
              .equals(other.getOutTimeResponse())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dateBodyCase_) {
        case 2:
          hash = (37 * hash) + OUTTIMERESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getOutTimeResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GameSystemModelMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameSystemModelMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameSystemModelMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameSystemModelMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameSystemModelMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameSystemModelMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameSystemModelMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameSystemModelMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameSystemModelMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GameSystemModelMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameSystemModelMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameSystemModelMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GameSystemModelMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameSystemModelMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameSystemModelMessage)
        GameSystemModelMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameSystemModel.internal_static_GameSystemModelMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameSystemModel.internal_static_GameSystemModelMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameSystemModelMessage.class, Builder.class);
      }

      // Construct using GameSystemModel.GameSystemModelMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dateBodyCase_ = 0;
        dateBody_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameSystemModel.internal_static_GameSystemModelMessage_descriptor;
      }

      @Override
      public GameSystemModelMessage getDefaultInstanceForType() {
        return GameSystemModelMessage.getDefaultInstance();
      }

      @Override
      public GameSystemModelMessage build() {
        GameSystemModelMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GameSystemModelMessage buildPartial() {
        GameSystemModelMessage result = new GameSystemModelMessage(this);
        result.dataType_ = dataType_;
        if (dateBodyCase_ == 2) {
          if (outTimeResponseBuilder_ == null) {
            result.dateBody_ = dateBody_;
          } else {
            result.dateBody_ = outTimeResponseBuilder_.build();
          }
        }
        result.dateBodyCase_ = dateBodyCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameSystemModelMessage) {
          return mergeFrom((GameSystemModelMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameSystemModelMessage other) {
        if (other == GameSystemModelMessage.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDateBodyCase()) {
          case OUTTIMERESPONSE: {
            mergeOutTimeResponse(other.getOutTimeResponse());
            break;
          }
          case DATEBODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GameSystemModelMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GameSystemModelMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dateBodyCase_ = 0;
      private Object dateBody_;
      public DateBodyCase
          getDateBodyCase() {
        return DateBodyCase.forNumber(
            dateBodyCase_);
      }

      public Builder clearDateBody() {
        dateBodyCase_ = 0;
        dateBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       *用date_type来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       *用date_type来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用date_type来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
       * @return The dataType.
       */
      @Override
      public DateType getDataType() {
        @SuppressWarnings("deprecation")
        DateType result = DateType.valueOf(dataType_);
        return result == null ? DateType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *用date_type来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(DateType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用date_type来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.GameSystemModelMessage.DateType data_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          OutTimeResponse, OutTimeResponse.Builder, OutTimeResponseOrBuilder> outTimeResponseBuilder_;
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       * @return Whether the outTimeResponse field is set.
       */
      @Override
      public boolean hasOutTimeResponse() {
        return dateBodyCase_ == 2;
      }
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       * @return The outTimeResponse.
       */
      @Override
      public OutTimeResponse getOutTimeResponse() {
        if (outTimeResponseBuilder_ == null) {
          if (dateBodyCase_ == 2) {
            return (OutTimeResponse) dateBody_;
          }
          return OutTimeResponse.getDefaultInstance();
        } else {
          if (dateBodyCase_ == 2) {
            return outTimeResponseBuilder_.getMessage();
          }
          return OutTimeResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       */
      public Builder setOutTimeResponse(OutTimeResponse value) {
        if (outTimeResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateBody_ = value;
          onChanged();
        } else {
          outTimeResponseBuilder_.setMessage(value);
        }
        dateBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       */
      public Builder setOutTimeResponse(
          OutTimeResponse.Builder builderForValue) {
        if (outTimeResponseBuilder_ == null) {
          dateBody_ = builderForValue.build();
          onChanged();
        } else {
          outTimeResponseBuilder_.setMessage(builderForValue.build());
        }
        dateBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       */
      public Builder mergeOutTimeResponse(OutTimeResponse value) {
        if (outTimeResponseBuilder_ == null) {
          if (dateBodyCase_ == 2 &&
              dateBody_ != OutTimeResponse.getDefaultInstance()) {
            dateBody_ = OutTimeResponse.newBuilder((OutTimeResponse) dateBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dateBody_ = value;
          }
          onChanged();
        } else {
          if (dateBodyCase_ == 2) {
            outTimeResponseBuilder_.mergeFrom(value);
          }
          outTimeResponseBuilder_.setMessage(value);
        }
        dateBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       */
      public Builder clearOutTimeResponse() {
        if (outTimeResponseBuilder_ == null) {
          if (dateBodyCase_ == 2) {
            dateBodyCase_ = 0;
            dateBody_ = null;
            onChanged();
          }
        } else {
          if (dateBodyCase_ == 2) {
            dateBodyCase_ = 0;
            dateBody_ = null;
          }
          outTimeResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       */
      public OutTimeResponse.Builder getOutTimeResponseBuilder() {
        return getOutTimeResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       */
      @Override
      public OutTimeResponseOrBuilder getOutTimeResponseOrBuilder() {
        if ((dateBodyCase_ == 2) && (outTimeResponseBuilder_ != null)) {
          return outTimeResponseBuilder_.getMessageOrBuilder();
        } else {
          if (dateBodyCase_ == 2) {
            return (OutTimeResponse) dateBody_;
          }
          return OutTimeResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.OutTimeResponse outTimeResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          OutTimeResponse, OutTimeResponse.Builder, OutTimeResponseOrBuilder>
          getOutTimeResponseFieldBuilder() {
        if (outTimeResponseBuilder_ == null) {
          if (!(dateBodyCase_ == 2)) {
            dateBody_ = OutTimeResponse.getDefaultInstance();
          }
          outTimeResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              OutTimeResponse, OutTimeResponse.Builder, OutTimeResponseOrBuilder>(
                  (OutTimeResponse) dateBody_,
                  getParentForChildren(),
                  isClean());
          dateBody_ = null;
        }
        dateBodyCase_ = 2;
        onChanged();;
        return outTimeResponseBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameSystemModelMessage)
    }

    // @@protoc_insertion_point(class_scope:GameSystemModelMessage)
    private static final GameSystemModelMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GameSystemModelMessage();
    }

    public static GameSystemModelMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameSystemModelMessage>
        PARSER = new com.google.protobuf.AbstractParser<GameSystemModelMessage>() {
      @Override
      public GameSystemModelMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameSystemModelMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameSystemModelMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GameSystemModelMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public GameSystemModelMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OutTimeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OutTimeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code OutTimeResponse}
   */
  public static final class OutTimeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OutTimeResponse)
      OutTimeResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OutTimeResponse.newBuilder() to construct.
    private OutTimeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OutTimeResponse() {
      message_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new OutTimeResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OutTimeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameSystemModel.internal_static_OutTimeResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameSystemModel.internal_static_OutTimeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OutTimeResponse.class, Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile Object message_;
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OutTimeResponse)) {
        return super.equals(obj);
      }
      OutTimeResponse other = (OutTimeResponse) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OutTimeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OutTimeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OutTimeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OutTimeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OutTimeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OutTimeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OutTimeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OutTimeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OutTimeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OutTimeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OutTimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OutTimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OutTimeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OutTimeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OutTimeResponse)
        OutTimeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameSystemModel.internal_static_OutTimeResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameSystemModel.internal_static_OutTimeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OutTimeResponse.class, Builder.class);
      }

      // Construct using GameSystemModel.OutTimeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameSystemModel.internal_static_OutTimeResponse_descriptor;
      }

      @Override
      public OutTimeResponse getDefaultInstanceForType() {
        return OutTimeResponse.getDefaultInstance();
      }

      @Override
      public OutTimeResponse build() {
        OutTimeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OutTimeResponse buildPartial() {
        OutTimeResponse result = new OutTimeResponse(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OutTimeResponse) {
          return mergeFrom((OutTimeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OutTimeResponse other) {
        if (other == OutTimeResponse.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OutTimeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OutTimeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OutTimeResponse)
    }

    // @@protoc_insertion_point(class_scope:OutTimeResponse)
    private static final OutTimeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OutTimeResponse();
    }

    public static OutTimeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OutTimeResponse>
        PARSER = new com.google.protobuf.AbstractParser<OutTimeResponse>() {
      @Override
      public OutTimeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OutTimeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OutTimeResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OutTimeResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public OutTimeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameSystemModelMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameSystemModelMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OutTimeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OutTimeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020GameSystem.proto\"\247\001\n\026GameSystemModelMe" +
      "ssage\0223\n\tdata_type\030\001 \001(\0162 .GameSystemMod" +
      "elMessage.DateType\022+\n\017outTimeResponse\030\002 " +
      "\001(\0132\020.OutTimeResponseH\000\"\037\n\010DateType\022\023\n\017O" +
      "utTimeResponse\020\000B\n\n\010dateBody\"\"\n\017OutTimeR" +
      "esponse\022\017\n\007message\030\001 \001(\tB\021B\017GameSystemMo" +
      "delb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GameSystemModelMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameSystemModelMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameSystemModelMessage_descriptor,
        new String[] { "DataType", "OutTimeResponse", "DateBody", });
    internal_static_OutTimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OutTimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OutTimeResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
